export const ErrorCode = {
  Forbidden: 'FORBIDDEN',
  InvalidCredentials: 'INVALID_CREDENTIALS',
  EmailAlreadyExists: 'EMAIL_ALREADY_EXISTS',
  DocumentCodeExists: 'DOCUMENT_CODE_EXISTS',
  DocumentInvalid: 'DOCUMENT_INVALID',
  DocumentNotFound: 'DOCUMENT_NOT_FOUND',
  DocumentReleaseConflict: 'DOCUMENT_RELEASE_CONFLICT',
  DocumentReleaseInvalid: 'DOCUMENT_RELEASE_INVALID',
  DocumentDecisionForbidden: 'DOCUMENT_DECISION_FORBIDDEN',
  DocumentWorkflowConflict: 'DOCUMENT_WORKFLOW_CONFLICT',
  DocumentWorkflowInvalid: 'DOCUMENT_WORKFLOW_INVALID',
  DocumentVersionConflict: 'DOCUMENT_VERSION_CONFLICT',
  InternalError: 'INTERNAL_ERROR',
  InvitationAlreadyExists: 'INVITATION_ALREADY_EXISTS',
  InvitationExpired: 'INVITATION_EXPIRED',
  InvitationInvalid: 'INVITATION_INVALID',
  LastAdministratorRequired: 'LAST_ADMINISTRATOR_REQUIRED',
  NotFound: 'NOT_FOUND',
  PasswordResetInvalid: 'PASSWORD_RESET_INVALID',
  PublicRegistrationDisabled: 'PUBLIC_REGISTRATION_DISABLED',
  RateLimitExceeded: 'RATE_LIMIT_EXCEEDED',
  ReauthenticationFailed: 'REAUTHENTICATION_FAILED',
  RoleInvalid: 'ROLE_INVALID',
  RoleNameExists: 'ROLE_NAME_EXISTS',
  SessionExpired: 'SESSION_EXPIRED',
  SessionRevoked: 'SESSION_REVOKED',
  SlugAlreadyExists: 'SLUG_ALREADY_EXISTS',
  Unauthorized: 'UNAUTHORIZED',
  ValidationError: 'VALIDATION_ERROR',
  VerificationTokenInvalid: 'VERIFICATION_TOKEN_INVALID',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
